sudo: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn install
after_success:
  - yarn run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
