sudo: false
language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
script:
  - yarn lint
after_success:
  - yarn release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
